version: "3.8"
services:
    mongodb:
        container_name: mongodb
        build: 
            context: mongodb/
        volumes:
        - ./data/mongodata:/data/mongodata 
        ports:
        - "27017:27017"
        command: mongod

    media-api:
        container_name: media-api
        build:
            context: ../media-api/
        volumes:
            - "../media-api/:/code/app"
        ports:
            - "51566:51566"
        depends_on:
            - "mongodb"
        environment:
            - ASPNETCORE_URLS=http://*:51566
        networks:
          - elk

networks: 
    elk:
        driver: bridge

volumes: 
    mongodata: