name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore "media-api/media-api.csproj"
      working-directory: ./media-api
    - name: Build
      run: dotnet build --no-restore "media-api/media-api.csproj"
      working-directory: ./media-api
    - name: Test
      run: dotnet test --no-build --verbosity normal "media-api.Tests/media-api.Tests.csproj"
      working-directory: ./media-api
